name: DockerApp
on: workflow_dispatch

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: image creation
      run: |
        docker-compose up -d
        docker images
    - name: Tag and push  image
      run: |
        echo -e "\e[34m[Tag and push Docker image]"
        docker  login -u e36ff0ce-ab2c-469d-bf19-b39f49e30311 -p 27a.vw-rrzE~b2efhJcKnJId88aVklflZl akshaytestpoc.azurecr.io   
        docker tag mcr.microsoft.com/azuredocs/azure-vote-front:v1 akshaytestpoc.azurecr.io/azure-vote-front:v1
        docker push akshaytestpoc.azurecr.io/azure-vote-front:v1
        az acr repository list --name akshaytestpoc.azurecr.io --output table
      shell: bash

