name: DockerApp
on: workflow_dispatch

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Login to ACR
      run: |
        #docker login -u $SP_APPID -p $SP_PASSWORD akshaytestpoc.azurecr.io
        docker  login -u e36ff0ce-ab2c-469d-bf19-b39f49e30311 -p 27a.vw-rrzE~b2efhJcKnJId88aVklflZl akshaytestpoc.azurecr.io        
      shell: bash

    - name: Tag and push  image
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        echo -e "\e[34m[Tag and push Docker image]"
        docker tag mcr.microsoft.com/azuredocs/azure-vote-front:v1 akshaytestpoc.azurecr.io/azure-vote-front:v1
        docker push akshaytestpoc.azurecr.io/azure-vote-front:v1
      shell: bash
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in aks
      run: |
        az acr repository list --name akshaytestpoc.azurecr.io --output table
      shell: bash
